/**
 * PR Fix — Auto-suggests fixes for failing PR checks.
 *
 * Analyzes failed check runs on a PR, reads the logs, and posts review comments
 * with specific fix suggestions. Focuses on actionable, file-level feedback.
 *
 * Environment variables:
 *   GITHUB_TOKEN  — GitHub token for API access
 *   PR_NUMBER     — PR number to analyze
 *   CHECK_RUN_ID  — Optional specific check run to analyze
 *   REPOSITORY    — owner/repo string
 *
 * Engagement Level: T2 (Advisor) — posts review comments, no direct edits.
 */

import { Octokit } from "@octokit/rest";
import { isDirectRun, runJob } from "./lib/entrypoint.js";

export interface FailedCheckInfo {
  name: string;
  html_url?: string | null;
  output?: { summary?: string | null } | null;
}

export const MAX_RELEVANT_FILES_LISTED = 10;

/** Narrows changed files to those most likely related to the named check. */
export function relevantFilesForCheck(checkName: string, changedFiles: string[]): string[] {
  const lower = checkName.toLowerCase();
  return changedFiles.filter((f) => {
    if (lower.includes("type")) return f.endsWith(".ts") || f.endsWith(".tsx");
    if (lower.includes("lint")) return f.endsWith(".ts") || f.endsWith(".js");
    if (lower.includes("test")) return f.includes("test") || f.includes("spec");
    return true;
  });
}

export function buildPrFixComment(failedChecks: FailedCheckInfo[], changedFiles: string[]): string {
  const lines: string[] = [
    "## 🔧 PR Fix Suggestions",
    "",
    `Found **${failedChecks.length}** failed check(s) on this PR.`,
    "",
  ];

  for (const check of failedChecks) {
    lines.push(`### ❌ ${check.name}`);
    lines.push("");

    if (check.output?.summary) {
      lines.push(check.output.summary);
    } else {
      lines.push(`Check [${check.name}](${check.html_url ?? ""}) failed. Review the logs for details.`);
    }

    const relevantFiles = relevantFilesForCheck(check.name, changedFiles);

    if (relevantFiles.length > 0) {
      lines.push("");
      lines.push("**Files to check:**");
      for (const file of relevantFiles.slice(0, MAX_RELEVANT_FILES_LISTED)) {
        lines.push(`- \`${file}\``);
      }
    }

    lines.push("");
  }

  lines.push(
    "---",
    "*Generated by GH-AW PR Fix — Engagement Level: T2 (Advisor)*",
  );

  return lines.join("\n");
}

export async function main(): Promise<void> {
  const token = process.env["GITHUB_TOKEN"];
  const prNumber = process.env["PR_NUMBER"];
  const repository = process.env["REPOSITORY"];

  if (!token || !prNumber || !repository) {
    console.log("PR Fix: Missing required environment variables. Skipping.");
    return;
  }

  const [owner, repo] = repository.split("/");
  if (!owner || !repo) {
    console.error("PR Fix: Invalid REPOSITORY format. Expected owner/repo.");
    process.exit(1);
  }

  const octokit = new Octokit({ auth: token });
  const prNum = parseInt(prNumber, 10);

  // Get the PR's check runs
  const { data: pr } = await octokit.pulls.get({
    owner,
    repo,
    pull_number: prNum,
  });

  const { data: checkRuns } = await octokit.checks.listForRef({
    owner,
    repo,
    ref: pr.head.sha,
    filter: "latest",
  });

  const failedChecks = checkRuns.check_runs.filter(
    (cr) => cr.conclusion === "failure",
  );

  if (failedChecks.length === 0) {
    console.log(`PR Fix: No failed checks on PR #${prNum}. Nothing to do.`);
    return;
  }

  // Get changed files in the PR
  const { data: files } = await octokit.pulls.listFiles({
    owner,
    repo,
    pull_number: prNum,
  });

  const changedFiles = files.map((f) => f.filename);

  const body = buildPrFixComment(failedChecks, changedFiles);

  await octokit.issues.createComment({
    owner,
    repo,
    issue_number: prNum,
    body,
  });

  console.log(`PR Fix: Posted suggestions to PR #${prNum}`);
}

if (isDirectRun(import.meta.url)) runJob("PR Fix", main);
