/**
 * Sub-Issue Closer — Automatically closes parent issues when all sub-issues complete.
 *
 * Finds open issues with sub-issues (identified by "[Parent Title]" pattern in title
 * or "has-plan" label), checks if all sub-issues are closed, and auto-closes
 * the parent with a summary comment.
 *
 * Environment variables:
 *   GITHUB_TOKEN   — GitHub token for API access
 *   REPOSITORY     — owner/repo string
 *
 * Engagement Level: T4 (Delegated) — closes issues automatically.
 */

import { Octokit } from "@octokit/rest";
import { isDirectRun, runJob } from "./lib/entrypoint.js";

export interface ParentIssue {
  number: number;
  title: string;
  subIssues: SubIssue[];
}

export interface SubIssue {
  number: number;
  title: string;
  state: "open" | "closed";
  closedAt?: string;
}

/** Minimal shape of an issue as returned by the GitHub API, for sub-issue matching. */
export interface IssueLike {
  number: number;
  title: string;
  state: string;
  body?: string | null;
  closed_at?: string | null;
}

export function isSubIssueOf(subTitle: string, parentTitle: string): boolean {
  // Check if sub-issue title starts with "[Parent Title]"
  const pattern = `[${parentTitle}]`;
  return subTitle.startsWith(pattern);
}

/** Finds sub-issues of `parent` by title prefix or "Sub-issue of #N" body marker. */
export function findSubIssues(parent: { number: number; title: string }, allIssues: IssueLike[]): SubIssue[] {
  const subIssues: SubIssue[] = [];

  for (const issue of allIssues) {
    if (issue.number === parent.number) continue;

    const toSubIssue = (): SubIssue => ({
      number: issue.number,
      title: issue.title,
      state: issue.state as "open" | "closed",
      closedAt: issue.closed_at ?? undefined,
    });

    if (isSubIssueOf(issue.title, parent.title)) {
      subIssues.push(toSubIssue());
    }

    // Boundary check so "#1" does not match "#10"
    if (issue.body && new RegExp(`Sub-issue of #${parent.number}(?!\\d)`).test(issue.body)) {
      if (!subIssues.some((s) => s.number === issue.number)) {
        subIssues.push(toSubIssue());
      }
    }
  }

  return subIssues;
}

/** A parent is ready to close only when it has sub-issues and none remain open. */
export function shouldCloseParent(subIssues: SubIssue[]): boolean {
  const open = subIssues.filter((s) => s.state === "open").length;
  const closed = subIssues.filter((s) => s.state === "closed").length;
  return open === 0 && closed > 0;
}

function isoDate(value: string | undefined): string | null {
  return value ? new Date(value).toISOString().split("T")[0]! : null;
}

export function buildClosingSummary(parent: ParentIssue): string {
  const sortedSubIssues = [...parent.subIssues].sort((a, b) => {
    const dateA = a.closedAt ? new Date(a.closedAt).getTime() : 0;
    const dateB = b.closedAt ? new Date(b.closedAt).getTime() : 0;
    return dateA - dateB;
  });

  const first = sortedSubIssues[0];
  const last = sortedSubIssues[sortedSubIssues.length - 1];

  return [
    "## ✅ All Sub-Issues Complete!",
    "",
    "This issue is being automatically closed because all sub-issues have been completed.",
    "",
    "### Completed Sub-Issues",
    "",
    ...sortedSubIssues.map((sub) => {
      const closedDate = isoDate(sub.closedAt) ?? "unknown";
      return `- [x] #${sub.number} — ${sub.title.replace(/^\[[^\]]+\]\s*\d+\/\d+:\s*/, "")} (closed ${closedDate})`;
    }),
    "",
    "### Summary",
    "",
    `- **Total sub-issues:** ${parent.subIssues.length}`,
    `- **First completed:** ${isoDate(first?.closedAt) ?? "N/A"}`,
    `- **Last completed:** ${isoDate(last?.closedAt) ?? "N/A"}`,
    "",
    "---",
    "*Generated by GH-AW Sub-Issue Closer — Engagement Level: T4 (Delegated)*",
  ].join("\n");
}

export async function main(): Promise<void> {
  const token = process.env["GITHUB_TOKEN"];
  const repository = process.env["REPOSITORY"];

  if (!token || !repository) {
    console.log("Sub-Issue Closer: Missing required environment variables. Skipping.");
    return;
  }

  const [owner, repo] = repository.split("/");
  if (!owner || !repo) {
    console.error("Sub-Issue Closer: Invalid REPOSITORY format. Expected owner/repo.");
    process.exit(1);
  }

  const octokit = new Octokit({ auth: token });

  // Fetch ALL open issues using pagination to avoid missing sub-issues beyond the first page
  const openIssues = await octokit.paginate(octokit.issues.listForRepo, {
    owner,
    repo,
    state: "open",
    per_page: 100,
  });

  // Fetch ALL closed issues using pagination so sub-issue matching is exhaustive
  const closedIssues = await octokit.paginate(octokit.issues.listForRepo, {
    owner,
    repo,
    state: "closed",
    per_page: 100,
  });

  const allIssues = [...openIssues, ...closedIssues];

  // Identify parent issues (those with "has-plan" label)
  const parentCandidates = openIssues.filter((issue) => {
    const labels = issue.labels.map((l) => (typeof l === "string" ? l : l.name)).filter(Boolean);
    return labels.includes("has-plan");
  });

  if (parentCandidates.length === 0) {
    console.log("Sub-Issue Closer: No parent issues with 'has-plan' label found. Skipping.");
    return;
  }

  console.log(`Sub-Issue Closer: Found ${parentCandidates.length} potential parent issues.`);

  const parentsToClose: ParentIssue[] = [];

  for (const parent of parentCandidates) {
    const subIssues = findSubIssues(parent, allIssues);

    if (subIssues.length === 0) {
      console.log(`Sub-Issue Closer: No sub-issues found for #${parent.number}. Skipping.`);
      continue;
    }

    const openSubIssues = subIssues.filter((s) => s.state === "open");
    const closedSubIssues = subIssues.filter((s) => s.state === "closed");

    console.log(
      `Sub-Issue Closer: #${parent.number} has ${subIssues.length} sub-issues ` +
        `(${closedSubIssues.length} closed, ${openSubIssues.length} open)`
    );

    if (shouldCloseParent(subIssues)) {
      parentsToClose.push({
        number: parent.number,
        title: parent.title,
        subIssues,
      });
    }
  }

  if (parentsToClose.length === 0) {
    console.log("Sub-Issue Closer: No parent issues ready to close. All have open sub-issues.");
    return;
  }

  // Close parent issues
  for (const parent of parentsToClose) {
    // Post comment
    await octokit.issues.createComment({
      owner,
      repo,
      issue_number: parent.number,
      body: buildClosingSummary(parent),
    });

    // Close the issue
    await octokit.issues.update({
      owner,
      repo,
      issue_number: parent.number,
      state: "closed",
      state_reason: "completed",
    });

    // Remove "has-plan" and add "completed" label
    try {
      await octokit.issues.removeLabel({
        owner,
        repo,
        issue_number: parent.number,
        name: "has-plan",
      });
    } catch {
      // Label might not exist
    }

    try {
      await octokit.issues.addLabels({
        owner,
        repo,
        issue_number: parent.number,
        labels: ["completed"],
      });
    } catch {
      // Label might not exist
    }

    console.log(`Sub-Issue Closer: Closed parent issue #${parent.number} with ${parent.subIssues.length} completed sub-issues.`);
  }

  console.log(`Sub-Issue Closer: Closed ${parentsToClose.length} parent issue(s).`);
}

if (isDirectRun(import.meta.url)) runJob("Sub-Issue Closer", main);
