/**
 * Workflow Health Manager — Monitors workflow health and reports issues.
 *
 * Checks all repository workflows for recent failures, stale runs, and
 * excessive run durations. Posts a health summary issue when problems are detected.
 *
 * Environment variables:
 *   GITHUB_TOKEN  — GitHub token for API access
 *   REPOSITORY    — owner/repo string
 *
 * Engagement Level: T2 (Advisor) — creates issues with health reports, no modifications.
 */

import { Octokit } from "@octokit/rest";
import { isDirectRun, runJob } from "./lib/entrypoint.js";

export interface WorkflowHealth {
  name: string;
  id: number;
  status: "healthy" | "degraded" | "failing";
  lastRun: string | null;
  lastConclusion: string | null;
  recentFailures: number;
  recentSuccesses: number;
  avgDurationMs: number;
}

export interface RunLike {
  conclusion: string | null;
  created_at: string;
  updated_at: string;
}

export const FAILING_THRESHOLD = 5;
export const DEGRADED_THRESHOLD = 2;

export function classifyStatus(failures: number): WorkflowHealth["status"] {
  if (failures >= FAILING_THRESHOLD) return "failing";
  if (failures >= DEGRADED_THRESHOLD) return "degraded";
  return "healthy";
}

/** Summarises the most recent runs (newest first) of one workflow. */
export function computeWorkflowHealth(
  wf: { id: number; name: string },
  recentRuns: RunLike[],
): WorkflowHealth {
  const failures = recentRuns.filter((r) => r.conclusion === "failure").length;
  const successes = recentRuns.filter((r) => r.conclusion === "success").length;

  const durations = recentRuns
    .filter((r) => r.updated_at && r.created_at)
    .map((r) => new Date(r.updated_at).getTime() - new Date(r.created_at).getTime());
  const avgDuration = durations.length > 0
    ? durations.reduce((a, b) => a + b, 0) / durations.length
    : 0;

  const lastRun = recentRuns[0];

  return {
    name: wf.name,
    id: wf.id,
    status: classifyStatus(failures),
    lastRun: lastRun?.created_at ?? null,
    lastConclusion: lastRun?.conclusion ?? null,
    recentFailures: failures,
    recentSuccesses: successes,
    avgDurationMs: Math.round(avgDuration),
  };
}

export const STATUS_EMOJI: Record<WorkflowHealth["status"], string> = {
  healthy: "✅",
  degraded: "⚠️",
  failing: "❌",
};

export function buildHealthReport(healthReports: WorkflowHealth[]): string {
  const problems = healthReports.filter((h) => h.status !== "healthy");

  const lines: string[] = [
    "## 🏥 Workflow Health Report",
    "",
    `**${problems.length}** workflow(s) need attention.`,
    "",
    "| Status | Workflow | Failures (last 10) | Avg Duration | Last Run |",
    "|--------|---------|-------------------|-------------|----------|",
  ];

  for (const h of healthReports) {
    const emoji = STATUS_EMOJI[h.status];
    const duration = h.avgDurationMs > 0 ? `${Math.round(h.avgDurationMs / 1000)}s` : "N/A";
    const lastRun = h.lastRun ? new Date(h.lastRun).toLocaleDateString() : "Never";
    lines.push(
      `| ${emoji} ${h.status} | ${h.name} | ${h.recentFailures}/10 | ${duration} | ${lastRun} |`,
    );
  }

  if (problems.length > 0) {
    lines.push("", "### Action Items", "");
    for (const p of problems) {
      if (p.status === "failing") {
        lines.push(`- 🔴 **${p.name}**: ${p.recentFailures} failures in last 10 runs. Investigate immediately.`);
      } else {
        lines.push(`- 🟡 **${p.name}**: ${p.recentFailures} failures in last 10 runs. Monitor closely.`);
      }
    }
  }

  lines.push(
    "",
    "---",
    "*Generated by GH-AW Workflow Health Manager — Engagement Level: T2 (Advisor)*",
  );

  return lines.join("\n");
}

export async function main(): Promise<void> {
  const token = process.env["GITHUB_TOKEN"];
  const repository = process.env["REPOSITORY"];

  if (!token || !repository) {
    console.log("Workflow Health: Missing required environment variables. Skipping.");
    return;
  }

  const [owner, repo] = repository.split("/");
  if (!owner || !repo) {
    console.error("Workflow Health: Invalid REPOSITORY format.");
    process.exit(1);
  }

  const octokit = new Octokit({ auth: token });

  // Get all workflows
  const { data: workflows } = await octokit.actions.listRepoWorkflows({
    owner,
    repo,
  });

  const healthReports: WorkflowHealth[] = [];

  for (const wf of workflows.workflows) {
    // Get recent runs
    const { data: runs } = await octokit.actions.listWorkflowRuns({
      owner,
      repo,
      workflow_id: wf.id,
      per_page: 10,
    });

    healthReports.push(computeWorkflowHealth(wf, runs.workflow_runs));
  }

  // Check if any issues need reporting
  const problems = healthReports.filter((h) => h.status !== "healthy");

  if (problems.length === 0) {
    console.log("Workflow Health: All workflows healthy.");
    console.log("");
    for (const h of healthReports) {
      console.log(`  ✅ ${h.name} — ${h.recentSuccesses}/10 successful, avg ${Math.round(h.avgDurationMs / 1000)}s`);
    }
    return;
  }

  // Build issue
  const body = buildHealthReport(healthReports);
  const today = new Date().toISOString().split("T")[0];

  await octokit.issues.create({
    owner,
    repo,
    title: `🏥 Workflow Health Alert — ${today}`,
    body,
    labels: ["infrastructure", "gh-aw"],
  });

  console.log(`Workflow Health: Created issue — ${problems.length} workflows need attention.`);
}

if (isDirectRun(import.meta.url)) runJob("Workflow Health", main);
